"""Presentation only: no risk, requirement, or route creation occurs here."""
from __future__ import annotations
import html, json
from .models import PRDiagnosticView

def render_pr_diagnostic_json(view: PRDiagnosticView) -> str: return json.dumps(view.to_dict(), ensure_ascii=False, indent=2) + "\n"
def render_pr_diagnostic_markdown(view: PRDiagnosticView) -> str:
    lines=["# PR 审查诊断", "", f"## {view.diagnostic_status}", view.change_summary["summary"], "", "## 风险位置"]
    for f in view.risk_findings: lines += [f"### {f.headline}", f.plain_language_explanation, f"涉及：{', '.join(f.affected_files)} {'；'.join(f.affected_line_ranges)}"]
    lines += ["", "## 下一步", view.recommended_route["message"], "", "当前为 AGM 本地审查工作台。这里的操作只记录 AGM 审查结果；不会修改代码，不会执行 git merge，也不会批准或合并 GitHub/GitLab 上的 PR。"]
    return "\n".join(lines)+"\n"
def render_pr_diagnostic_html(view: PRDiagnosticView) -> str:
    esc=html.escape; risks="".join(f"<article><h3>{esc(f.headline)}</h3><p><strong>{esc('；'.join(f.affected_files))} {'；'.join(f.affected_line_ranges)}</strong></p><p>{esc(f.plain_language_explanation)}</p></article>" for f in view.risk_findings); gaps="".join(f"<article class=gap><h3>{esc(f.headline)}</h3><p>{esc(f.plain_language_explanation)}</p><p><strong>缺少什么：</strong>{esc(f.gap)}</p></article>" for f in view.evidence_gaps) or "<p>当前无需额外操作。</p>"; objects="".join(f"<article><h3>{esc(o.title)}</h3><p>{esc(o.plain_language_summary)}</p>{('<pre>'+esc(o.inline_content)+'</pre>') if o.inline_content else '<p>该材料当前不可查看。</p>'}</article>" for o in view.inspection_objects); actions="".join(f"<article><h3>{esc(a.label)}</h3><p><strong>会：</strong>{esc('；'.join(a.will_do))}</p><p><strong>不会：</strong>{esc('；'.join(a.will_not_do))}</p></article>" for a in view.action_effect_boundaries)
    return f'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PR 审查诊断</title><style>body{{margin:0;background:#f3f6f8;font:16px/1.55 system-ui;color:#18212f;overflow-wrap:anywhere}}main{{max-width:1040px;margin:auto;padding:16px}}section,article,details{{background:white;border:1px solid #dbe2ea;border-radius:12px;padding:16px;margin:14px 0}}header{{background:#153452;color:white;padding:20px;border-radius:12px}}.status,.gap{{border-left:6px solid #a64b17}}.grid{{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}}pre{{white-space:pre-wrap;overflow:auto}}@media(max-width:720px){{main{{padding:8px}}.grid{{grid-template-columns:1fr}}}}</style><main><header><h1>PR 审查诊断</h1><p>当前为 AGM 本地审查工作台：操作只记录 AGM 审查结果，不会修改代码、批准或合并平台 PR。</p></header><section class=status><h2>{esc(view.diagnostic_status)}</h2><p>{esc(view.recommended_route['message'])}</p><p><strong>下一步：</strong>{esc(view.recommended_route['owner'])}</p></section><section><h2>这次 PR 改了什么</h2><p>{esc(str(view.change_summary['summary']))}</p><p>{esc('；'.join(view.change_summary['files']))}</p></section><section><h2>风险位置与原因</h2>{risks}</section><section><h2>项目要求与当前情况</h2><div class=grid><article><h3>本类修改通常需要</h3><ul>{''.join('<li>'+esc(x['title'])+'</li>' for x in view.expected_requirements)}</ul></article><article><h3>当前实际情况</h3><ul>{''.join('<li>'+esc(x['state'])+'：'+esc(x['title'])+'</li>' for x in view.expected_requirements)}</ul></article></div></section><section><h2>缺失和异常</h2>{gaps}</section><section><h2>具体检查对象</h2>{objects}</section><section><h2>页面操作边界</h2>{actions}</section><details><summary>技术与治理详情</summary><pre>{esc(json.dumps(view.technical_derivation,ensure_ascii=False,indent=2))}</pre></details></main></html>'''
